server:
  port: 8080
spring:
  application:
    name: MultiTenancy
  datasource:
    url: 'jdbc:postgresql://localhost:5432/multitenancy?ApplicationName=MultiTenancy'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
